[package]
name = "otomaiv5"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "otomaiv5_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
device_query = "2.1.0" # <-- AJOUTE ÇA
serde = { version = "1", features = ["derive"] }
serde_json = "1"
enigo = "0.2"
regex = "1.10"
tauri-plugin-http = "2"
tauri-plugin-fs = "2"
rdev = "0.5"
screenshots = "0.8"  
image = "0.24"
strsim = "0.11.0"
tauri-plugin-notification = "2"
xcap = "0.0.9"
opencv = "0.94"
anyhow = "1.0"
    

[dependencies.windows]
version = "0.58" # Ou la version la plus récente
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
]

[profile.release]
panic = "abort"     # En cas de crash, on coupe tout (plus léger)
codegen-units = 1   # Compile plus lentement, mais le code final est mieux optimisé
lto = true          # "Link Time Optimization" : Fusionne tout le code pour l'optimiser en bloc
opt-level = 3       # Niveau d'optimisation maximum
strip = true        # Retire les infos de debug pour réduire la taille de l'exe
